version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${frog}
      - MYSQL_DATABASE=${mydatabasesb}

  apache:
    build:
      context: .
    container_name: apache-n-php-container
    restart: always
    ports:
      - "13680:80"
    volumes:
      - ./web:/var/www/html/
    depends_on:
      - mysql